POST http://localhost:8080/api/img-category
Content-Type: application/json

{
  "keywords": [
      "macbook air",
      "apple",
      "laptop",
      "computer",
      "rose gold",
      "keyboard"
  ]
}